import { Routes } from '@angular/router';

export const routes: Routes = [
    { path: 'adiantamento', loadComponent: () => import('./components/features/adiantamento/adiantamento.component').then(m => m.AdiantamentoComponent) },
    { path: 'acrescimo', loadComponent: () => import('./components/features/acrescimo/acrescimo.component').then(m => m.AcrescimoComponent) },
    { path: 'banco', loadComponent: () => import('./components/features/banco/banco.component').then(m => m.BancoComponent) },
    { path: 'conta', loadComponent: () => import('./components/features/conta/conta.component').then(m => m.ContaComponent) },
    { path: 'contato', loadComponent: () => import('./components/features/contato/contato.component').then(m => m.ContatoComponent) },
    { path: 'dadospessoais', loadComponent: () => import('./components/features/dadospessoais/dadospessoais.component').then(m => m.DadosPessoaisComponent) },
    { path: 'dadostrabalho', loadComponent: () => import('./components/features/dadostrabalho/dadostrabalho.component').then(m => m.DadosTrabalhoComponent) },
    { path: 'dashboard', loadComponent: () => import('./components/dashboard/dashboard.component').then(m => m.DashboardComponent) },
    { path: 'documento', loadComponent: () => import('./components/features/documento/documento.component').then(m => m.DocumentoComponent) },
    { path: 'dependente', loadComponent: () => import('./components/features/dependente/dependente.component').then(m => m.DependenteComponent) },
    { path: 'empresa', loadComponent: () => import('./components/features/empresa/empresa.component').then(m => m.EmpresaComponent) },
    { path: 'endereco', loadComponent: () => import('./components/features/endereco/endereco.component').then(m => m.EnderecoComponent) },
    { path: 'estado', loadComponent: () => import('./components/features/estado/estado.component').then(m => m.EstadoComponent) },
    { path: 'escala', loadComponent: () => import('./components/features/escala/escala.component').then(m => m.EscalaComponent) },
    { path: 'escolaridade', loadComponent: () => import('./components/features/escolaridade/escolaridade.component').then(m => m.EscolaridadeComponent) },
    { path: 'estadocivil', loadComponent: () => import('./components/features/estadoCivil/estadoCivil.component').then(m => m.EstadoCivilComponent) },
    { path: 'funcao', loadComponent: () => import('./components/features/funcao/funcao.component').then(m => m.FuncaoComponent) },
    { path: 'funcaoRegistro', loadComponent: () => import('./components/features/funcaoRegistro/funcaoRegistro.component').then(m => m.FuncaoRegistroComponent) },
    { path: 'municipio', loadComponent: () => import('./components/features/municipio/municipio.component').then(m => m.MunicipioComponent) },
    { path: 'nacionalidade', loadComponent: () => import('./components/features/nacionalidade/nacionalidade.component').then(m => m.NacionalidadeComponent) },
    { path: 'periodo', loadComponent: () => import('./components/features/periodo/periodo.component').then(m => m.PeriodoComponent) },
    { path: 'pessoa', loadComponent: () => import('./components/features/pessoa/pessoa.component').then(m => m.PessoaComponent) },
    { path: 'salario', loadComponent: () => import('./components/features/salario/salario.component').then(m => m.SalarioComponent) },
    { path: 'setor', loadComponent: () => import('./components/features/setor/setor.component').then(m => m.SetorComponent) },
    { path: 'unidade', loadComponent: () => import('./components/features/unidade/unidade.component').then(m => m.UnidadeComponent) },
    { path: 'login', loadComponent: () => import('./components/login/login.component').then(m => m.LoginComponent) },
    { path: 'hora-extra', loadComponent: () => import('./components/features/hora-extra/hora-extra.component').then(m => m.HoraExtraComponent) },
    { path: 'hora-falta', loadComponent: () => import('./components/features/hora-falta/hora-falta.component').then(m => m.HoraFaltaComponent) },
    { path: 'desconto', loadComponent: () => import('./components/features/desconto/desconto.component').then(m => m.DescontoComponent) },
    { path: 'tipo-hora', loadComponent: () => import('./components/features/tipo-hora/tipo-hora.component').then(m => m.TipoHoraComponent) },
    
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: '**', redirectTo: 'dashboard' },
];